<a href="https://colab.research.google.com/github/RsdTanmoy/Machine-Learning-Numpy/blob/main/Numpy_Practical_8(random_sampling).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Random Sampling With Numpy**

In [ ]:
import numpy as np

In [ ]:
import random

**np.random.random()**

In [ ]:
np.random.random(1)

array([0.34791613])

In [ ]:
np.random.random((3,3))

array([[0.94215559, 0.10459942, 0.18181019],
       [0.77712091, 0.82935102, 0.37672382],
       [0.11479258, 0.37261105, 0.53777758]])

**np.random.randint()**

In [ ]:
np.random.randint(1,4)

1

In [ ]:
np.random.randint(1,4,(4,4))

array([[1, 1, 2, 2],
       [3, 1, 1, 3],
       [3, 1, 2, 1],
       [2, 1, 2, 1]])

In [ ]:
np.random.randint(1,4,(2,4,4))

array([[[3, 3, 2, 3],
        [3, 3, 2, 2],
        [2, 1, 1, 2],
        [2, 2, 1, 1]],

       [[1, 3, 1, 1],
        [1, 1, 3, 2],
        [1, 2, 1, 1],
        [2, 2, 3, 3]]])

In [ ]:
np.random.randint(1,4,(3,4,4))

array([[[2, 3, 3, 3],
        [3, 2, 1, 2],
        [3, 1, 2, 2],
        [3, 1, 3, 3]],

       [[3, 1, 3, 1],
        [2, 3, 2, 2],
        [3, 2, 1, 2],
        [1, 3, 1, 1]],

       [[3, 3, 2, 3],
        [2, 1, 2, 1],
        [3, 1, 2, 3],
        [3, 3, 1, 3]]])

**np.random.seed()**

In [ ]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [ ]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

**np.random.rand()**

In [ ]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [ ]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

**np.random.randn()**

In [ ]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

**np.random.choice()**

In [ ]:
x=[1,2,3,4]
np.random.choice(x)

1

In [ ]:
for i in range(10):
  print(np.random.choice(x))

3
3
4
1
1
1
1
3
3
2


**np.random.permutation()**

In [ ]:
np.random.permutation(x)

array([4, 3, 1, 2])

In [ ]:
np.random.permutation(x)

array([1, 4, 2, 3])