<a href="https://colab.research.google.com/github/RsdTanmoy/Machine-Learning-Numpy/blob/main/Numpy_Practical_3(Function).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**np.arange() Python NumPy Function**

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr_1d = np.arange(1,13,2)
print(arr_1d)

[ 1  3  5  7  9 11]


**np.linspace() Python NumPy Function**

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**np.reshape() Python NumPy Function**

In [ ]:
arr_2d = ar_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
arr_2d = ar_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr_3d = ar_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
a_3d = np.arange(1,13).reshape(2,6)
print(a_3d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**np.ravel() Python NumPy Function**

In [ ]:
a_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**np.flatten() Python NumPy Function**

In [ ]:
a_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**np.transpose() Python NumPy Function**

In [ ]:
a_3d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])