<a href="https://colab.research.google.com/github/RsdTanmoy/Machine-Learning-Numpy/blob/main/Numpy_Practical_1(NumPy_Array).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**create one and multidimensional array**

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


check type

In [ ]:
type(arr_1d)

numpy.ndarray

**check dimension**

In [ ]:
arr_1d.ndim

1

In [ ]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(arr_2d)

numpy.ndarray

In [ ]:
arr_2d.ndim

2

**check size** 

In [ ]:
arr_1d.size

5

In [ ]:
arr_2d.size

8

In [ ]:
arr_2d.shape

(2, 4)

In [ ]:
arr_2d.dtype

dtype('int64')

In [ ]:
arr_1d

array([1, 2, 3, 4, 5])

In [ ]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])