<a href="https://colab.research.google.com/github/RsdTanmoy/Machine-Learning-Numpy/blob/main/Numpy_Practical_2(Function).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**np.ones() Python NumPy Function**

In [ ]:
import numpy as np

In [ ]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
mat_1s = np.ones(5)
print(mat_1s)

[1. 1. 1. 1. 1.]


In [ ]:
mat_1s.dtype

dtype('float64')

In [ ]:
matrix_1s = np.ones((3,4))
print(matrix_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
mat_1s = np.ones((3,4), dtype= int)
print(mat_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**np.zeros() Python NumPy Function**

In [ ]:
mx_0s = np.zeros((3,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
mat_0s = np.zeros((3,4), dtype= int)
print(mat_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
mat_0s = np.zeros((3,4), dtype= bool)
print(mat_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


**np.empty() Python NumPy Function**

In [ ]:
mat_0s = np.zeros((3,4), dtype= str)
print(mat_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [ ]:
em_str=''
print(bool(em_str))

False
