<a href="https://colab.research.google.com/github/RsdTanmoy/Machine-Learning-Numpy/blob/main/Numpy_Practical_4(functions_and_operators).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**+ operator for addition**

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.arange(1,10).reshape(3,3)
arr_2 = np.arange(1,10).reshape(3,3)

print(arr_1)
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr_1 + arr_2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**np.add() NumPy function**

In [ ]:
np.add(arr_1, arr_2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**- operator for subtraction**

In [ ]:
arr_1 - arr_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**np.subtract**

In [ ]:
np.subtract(arr_1, arr_2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**/ operator for division**

In [ ]:
arr_1 / arr_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**np.divid() NumPy function**

In [ ]:
np.divide(arr_1, arr_2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**multiply operator**

In [ ]:
arr_1 * arr_2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**np.multiply**

In [ ]:
np.multiply(arr_1, arr_2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**@ operator for matrix product**

In [ ]:
arr_1 @ arr_2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

**np.dot() for matrix product**

In [ ]:
arr_1.dot(arr_2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**np.max() & np.min() for find maximum and minimum value**

In [ ]:
arr_1.max()

9

In [ ]:
arr_1.min()

1

**np.argmax() & np.argmin() for find index of maximum and minimum value**

In [ ]:
arr_1.argmax()

8

In [ ]:
arr_1.argmin()

0

In [ ]:
arr_1.max(axis=0)

array([7, 8, 9])

In [ ]:
arr_1.max(axis=1)

array([3, 6, 9])

**np.sum() to calculate sum**

In [ ]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr_2)

45

In [ ]:
np.sum(arr_2, axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr_2, axis=1)

array([ 6, 15, 24])

**np.mean() to calculate average**

In [ ]:
np.mean(arr_1)

5.0

**square root**

In [ ]:
np.sqrt(arr_1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

**np.std() to calculate standerd division**

In [ ]:
np.std(arr_1)

2.581988897471611

**np.exp()  to calculate exponent**

In [ ]:
np.exp(arr_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

**np.log()  to calculate natural log**

In [ ]:
np.log(arr_1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

**np.log10()  to calculate log to base 10**

In [ ]:
np.log10(arr_1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])